### PR TITLE
ONCEHUB-65303 Upgrade angular version to 16.x

### PR DESCRIPTION
**Pull request by Areeb2512**
Updated @angular/core and ng update @angular-eslint/schematics
https://scheduleonce.atlassian.net/browse/ONCEHUB-65303

### CODE REVIEW

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **vaibhavso**
You can assign the PR to them by writing `/assign @vaibhavso` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/qa/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by siddharth-so — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[siddharth-so](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758314 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **vaibhavso**
You can assign the PR to them by writing `/assign @vaibhavso` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/qa/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sharmaaayush-OH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[sharmaaayush-OH](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758518 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758314 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **vaibhavso**
You can assign the PR to them by writing `/assign @vaibhavso` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/qa/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kaushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sharmaaayush-OH](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758518 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758314 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529759317 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/qa/OWNERS)~~ [so-kaushal]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sharmaaayush-OH](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758518 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758314 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529759317 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/qa/OWNERS)~~ [so-kaushal]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[sharmaaayush-OH](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758518 "Approved")*, *[siddharth-so](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#pullrequestreview-1529758314 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/knowledgeowl-angular/pull/122#issuecomment-1635402172 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/qa/OWNERS)~~ [so-kaushal]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
