### PR TITLE
updating branch to publish from master

### PR DESCRIPTION
**Pull request by so-hvats**

### CODE REVIEW

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **amitbishtoh**
You can assign the PR to them by writing `/assign @amitbishtoh` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by OhTanishJain — APPROVED** [review]
/approve

**Review by OhTanishJain — COMMENTED** [review]
/assign @amitbishtoh

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[OhTanishJain](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#pullrequestreview-931563514 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#issuecomment-1088490429 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **amitbishtoh**
You can assign the PR to them by writing `/assign @amitbishtoh` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *[OhTanishJain](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#pullrequestreview-931563514 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#issuecomment-1088490429 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sumitsharma22 — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[OhTanishJain](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#pullrequestreview-931563514 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#issuecomment-1088490429 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#pullrequestreview-931578143 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/master/OWNERS)~~ [sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[OhTanishJain](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#pullrequestreview-931563514 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#issuecomment-1088490429 "Approved")*, *[sumitsharma22](https://github.com/scheduleonce/knowledgeowl-angular/pull/78#issuecomment-1088497581 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fknowledgeowl-angular).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/knowledgeowl-angular/blob/master/OWNERS)~~ [sumitsharma22]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
